CC = gcc
EXEC=exec.c
EXEC_BIN=exec

FORK_EXEC=fork_exec.c
FORK_EXEC_BIN=fork_exec

SIMPLE_TRACE=simple_trace.c
SIMPLE_TRACE_BIN=simple_trace

TRACER=tracer.c
TRACER_BIN=tracer

all:
	$(CC) -o $(EXEC_BIN) $(EXEC)
	$(CC) -o $(FORK_EXEC_BIN) $(FORK_EXEC)
	$(CC) -o $(SIMPLE_TRACE_BIN) $(SIMPLE_TRACE)
	$(CC) -o $(TRACER_BIN) $(TRACER)
	
